colors:
  pink: "#ff79c6"
  purple: "#bd93f9"
  cyan: "#8be9fd"
  green: "#50fa7b"
  yellow: "#f1fa8c"
  orange: "#ffb86c"

color_cycle:
  green
  cyan
  purple
  pink
  yellow

page_colors:
  _: purple
  _about: green
  _dracula: pink
  _blog: cyan
  _why_pgp: yellow
  _documents_cypherpunks_manifesto_md: purple
  _documents_technology_usage_manifesto_md: orange
